export const SECTIONS = [
  {
    key: "notices",
    label: "Notices",
    icon: "bell",
    columns: ["Title", "Date", "Category"],
    apiPath: "/api/notices",
    addFields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "category", label: "Category", type: "select", options: ["General", "Academic", "Event", "Urgent"], required: true },
      { key: "date", label: "Date", type: "date", required: true },
      { key: "body", label: "Content", type: "textarea" },
    ],
  },
  {
    key: "advisors",
    label: "Advisors",
    icon: "users",
    columns: ["Name", "Email", "Designation"],
    apiPath: "/api/advisors",
    addFields: [
      { key: "name", label: "Full Name", type: "text", required: true },
      { key: "email", label: "Email", type: "email", required: true },
      { key: "designation", label: "Designation", type: "text", required: true },
      { key: "department", label: "Department", type: "text" },
      { key: "photoUrl", label: "Photo URL", type: "url" },
    ],
  },
  {
    key: "committee",
    label: "Committee",
    icon: "building",
    columns: ["Name", "Email", "Role"],
    apiPath: "/committee",
    addFields: [
      { key: "name", label: "Full Name", type: "text", required: true },
      { key: "email", label: "Email", type: "email", required: true },
      {
        key: "role",
        label: "Role",
        type: "select",
        options: [
          "President",
          "Vice President",
          "Secretary",
          "Treasurer",
          "General Member",
          "Executive Member",
        ],
        required: true,
      },
      { key: "batch", label: "Batch", type: "text" },
      { key: "photoUrl", label: "Photo URL", type: "url" },
    ],
    subSections: [
      {
        key: "committee-general",
        label: "General Members",
        filter: (r) => r.role === "General Member",
      },
      {
        key: "committee-executive",
        label: "Executive Members",
        filter: (r) => r.role !== "General Member",
      },
    ],
  },
  {
    key: "alumni",
    label: "Alumni",
    icon: "graduation",
    columns: ["Name", "Email", "Batch"],
    apiPath: "/api/alumni",
    addFields: [
      { key: "name", label: "Full Name", type: "text", required: true },
      { key: "email", label: "Email", type: "email", required: true },
      { key: "batch", label: "Batch", type: "text", required: true },
      { key: "designation", label: "Designation", type: "text" },
      { key: "company", label: "Company", type: "text" },
      { key: "linkedin", label: "LinkedIn URL", type: "url" },
    ],
  },
  {
    key: "blogs",
    label: "Blogs",
    icon: "edit",
    columns: ["Title", "Author", "Status"],
    apiPath: "/api/blogs",
    addFields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "author", label: "Author", type: "text", required: true },
      {
        key: "category",
        label: "Category",
        type: "select",
        options: ["Achievement", "Event", "Research", "News", "Workshop"],
      },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: ["Draft", "Published"],
        required: true,
      },
      { key: "excerpt", label: "Excerpt", type: "textarea" },
      { key: "imageUrl", label: "Cover Image URL", type: "url" },
    ],
  },
  {
    key: "membership",
    label: "Membership",
    icon: "gift",
    columns: ["Name", "Email", "Status"],
    apiPath: "/api/membership",
    readOnly: true,
    addFields: [],
  },
];
